--CREA PARAMETROS PARA LA ENTIDAD D_URMBJSSRVCS0050 EN params_des
DELETE FROM params_des WHERE ENTIDAD= 'D_URMBJSSRVCS0050';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_RUTA','/home/nae105215/RAW/USERDAS/OTC_T_V_BAJAS_SERVICIOS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_TABLA','otc_t_v_bajas_servicios','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_DSN','MyMSSQLServer','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_DATABASE','telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_USUARIO','userdas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_PASSWORD','CM3wm#$9iiHr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_CERTIFCADO','Yes','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_ESQUEMA_SQLSERVER','dbo','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_TABLA_SQLSERVER','v_bajas_servicios_DAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_RUTA_SPARK','/usr/hdp/current/spark2-client/bin/spark-submit','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMBJSSRVCS0050','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','0');

conn = pyodbc.connect(
    driver,"com.microsoft.sqlserver.jdbc.SQLServerDriver",
    server='10.122.7.242,14335',
    database=vDatabase,
    uid=vUid,
    pwd=vPwd)


select * from params_des WHERE ENTIDAD='D_URMBJSSRVCS0050' order by PARAMETRO;



--CREA PARAMETROS PARA LA ENTIDAD D_URMDGTGNDS0020 EN params_des
DELETE FROM params_des WHERE ENTIDAD= 'D_URMDGTGNDS0020';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_RUTA','/home/nae105215/RAW/USERDAS/OTC_T_V_DIGITALES_GANADAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_TABLA','otc_t_v_digitales_ganadas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_DATABASE','telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_USUARIO','userdas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_PASSWORD','CM3wm#$9iiHr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_ESQUEMA_SQLSERVER','dbo','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_TABLA_SQLSERVER','v_digitales_ganadas_DAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTGNDS0020','VAL_RUTA_SPARK','/usr/hdp/current/spark2-client/bin/spark-submit','0','0');

select * from params_des WHERE ENTIDAD='D_URMDGTGNDS0020' order by PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD D_URMTRDCNLIMPLMNTD0040 EN params_des
DELETE FROM params_des WHERE ENTIDAD= 'D_URMTRDCNLIMPLMNTD0040';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_RUTA','/home/nae105215/RAW/USERDAS/OTC_T_V_TRADICIONALES_IMPLEMENTADAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_TABLA','otc_t_v_tradicionales_implementadas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_DATABASE','telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_USUARIO','userdas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_PASSWORD','CM3wm#$9iiHr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_ESQUEMA_SQLSERVER','dbo','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_TABLA_SQLSERVER','v_tradicionales_implementadas_DAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLIMPLMNTD0040','VAL_RUTA_SPARK','/usr/hdp/current/spark2-client/bin/spark-submit','0','0');

select * from params_des WHERE ENTIDAD='D_URMTRDCNLIMPLMNTD0040' order by PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD D_URMTRDCNLSGNDS0030 EN params_des
DELETE FROM params_des WHERE ENTIDAD= 'D_URMTRDCNLSGNDS0030';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_RUTA','/home/nae105215/RAW/USERDAS/OTC_T_V_TRADICIONALES_GANADAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_TABLA','otc_t_v_tradicionales_ganadas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_DATABASE','telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_USUARIO','userdas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_PASSWORD','CM3wm#$9iiHr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_ESQUEMA_SQLSERVER','dbo','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_TABLA_SQLSERVER','v_tradicionales_ganadas_DAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMTRDCNLSGNDS0030','VAL_RUTA_SPARK','/usr/hdp/current/spark2-client/bin/spark-submit','0','0');

select * from params_des WHERE ENTIDAD='D_URMTRDCNLSGNDS0030' order by PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD D_URMDGTIMPLMNTDS0010 EN params_des
DELETE FROM params_des WHERE ENTIDAD= 'D_URMDGTIMPLMNTDS0010';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_RUTA','/home/nae105215/RAW/USERDAS/OTC_T_V_DIGITALES_IMPLEMENTADAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_ESQUEMA','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_TABLA','otc_t_v_digitales_implementadas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_DATABASE','telefonica','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_USUARIO','userdas','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_PASSWORD','CM3wm#$9iiHr','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_ESQUEMA_SQLSERVER','dbo','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_TABLA_SQLSERVER','v_digitales_implementadas_DAS','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_URMDGTIMPLMNTDS0010','VAL_RUTA_SPARK','/usr/hdp/current/spark2-client/bin/spark-submit','0','0');

select * from params_des WHERE ENTIDAD='D_URMDGTIMPLMNTDS0010' order by PARAMETRO;



