--CREA PARAMETROS PARA LA ENTIDAD URMBJSSRVCS0050 EN params
DELETE FROM params WHERE ENTIDAD= 'URMBJSSRVCS0050';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_RUTA','/RAW/USERDAS/OTC_T_V_BAJAS_SERVICIOS','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_ESQUEMA','db_userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_TABLA','otc_t_v_bajas_servicios','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_COLA_EJECUCION','default','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_DATABASE','telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_USUARIO','userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_PASSWORD','CM3wm#$9iiHr','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_ESQUEMA_SQLSERVER','dbo','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_TABLA_SQLSERVER','v_bajas_servicios_DAS','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMBJSSRVCS0050','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','1');
SELECT * FROM params WHERE ENTIDAD='URMBJSSRVCS0050' ORDER BY PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD URMDGTGNDS0020 EN params
DELETE FROM params WHERE ENTIDAD= 'URMDGTGNDS0020';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_RUTA','/RAW/USERDAS/OTC_T_V_DIGITALES_GANADAS','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_ESQUEMA','db_userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_TABLA','otc_t_v_digitales_ganadas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_COLA_EJECUCION','default','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_DATABASE','telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_USUARIO','userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_PASSWORD','CM3wm#$9iiHr','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_ESQUEMA_SQLSERVER','dbo','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTGNDS0020','VAL_TABLA_SQLSERVER','v_digitales_ganadas_DAS','0','1');
select * from params WHERE ENTIDAD='URMDGTGNDS0020' ORDER BY PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD URMTRDCNLIMPLMNTD0040 EN params
DELETE FROM params WHERE ENTIDAD= 'URMTRDCNLIMPLMNTD0040';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_RUTA','/RAW/USERDAS/OTC_T_V_TRADICIONALES_IMPLEMENTADAS','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_ESQUEMA','db_userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_TABLA','otc_t_v_tradicionales_implementadas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_COLA_EJECUCION','default','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_DATABASE','telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_USUARIO','userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_PASSWORD','CM3wm#$9iiHr','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_ESQUEMA_SQLSERVER','dbo','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLIMPLMNTD0040','VAL_TABLA_SQLSERVER','v_tradicionales_implementadas_DAS','0','1');
select * from params WHERE ENTIDAD='URMTRDCNLIMPLMNTD0040' ORDER BY PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD URMTRDCNLSGNDS0030 EN params
DELETE FROM params WHERE ENTIDAD= 'URMTRDCNLSGNDS0030';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_RUTA','/RAW/USERDAS/OTC_T_V_TRADICIONALES_GANADAS','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_ESQUEMA','db_userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_TABLA','otc_t_v_tradicionales_ganadas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_COLA_EJECUCION','default','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_DATABASE','telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_USUARIO','userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_PASSWORD','CM3wm#$9iiHr','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_ESQUEMA_SQLSERVER','dbo','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMTRDCNLSGNDS0030','VAL_TABLA_SQLSERVER','v_tradicionales_ganadas_DAS','0','1');
SELECT * FROM params WHERE ENTIDAD='URMTRDCNLSGNDS0030' ORDER BY PARAMETRO;

--CREA PARAMETROS PARA LA ENTIDAD URMDGTIMPLMNTDS0010 EN params
DELETE FROM params WHERE ENTIDAD= 'URMDGTIMPLMNTDS0010';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_RUTA','/RAW/USERDAS/OTC_T_V_DIGITALES_IMPLEMENTADAS','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_ESQUEMA','db_userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_TABLA','otc_t_v_digitales_implementadas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_COLA_EJECUCION','default','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_URL','jdbc:sqlserver://10.122.7.242:14335;databaseName=telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_DATABASE','telefonica','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_USUARIO','userdas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_PASSWORD','CM3wm#$9iiHr','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_ESQUEMA_SQLSERVER','dbo','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('URMDGTIMPLMNTDS0010','VAL_TABLA_SQLSERVER','v_digitales_implementadas_DAS','0','1');
SELECT * FROM params WHERE ENTIDAD='URMDGTIMPLMNTDS0010' ORDER BY PARAMETRO;

--CREACION DE PARAMETROS EN params PARA LA SHELL PRINCIPAL DE CONECTIVIDAD
DELETE FROM params WHERE ENTIDAD= 'EXTRCNCTVDD0040';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','PARAM1_FECHA','date_format(sysdate(),''%Y%m%d'')','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','PARAM2_VAL_RUTA','''/RGenerator/reportes/EXT_CONECTIVIDAD''','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','ETAPA','1','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_COLA_EJECUCION','default','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','SHELL','/RGenerator/reportes/EXT_CONECTIVIDAD/bin/OTC_T_EXT_CONECTIVIDAD.sh','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_ESQUEMA','db_reportes','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_TABLA','otc_t_ext_conectividad','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_NOM_ARCHIVO','Extractor_Conectividad.txt','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_FTP_PUERTO','22','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_FTP_USER','telefonicaecuadorprod','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_FTP_HOSTNAME','ftp.cloud.varicent.com','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_FTP_PASS','RqiZ2lkJmeiQTi2hvRwd','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('EXTRCNCTVDD0040','VAL_FTP_RUTA','/Data','0','1');
SELECT * FROM params WHERE ENTIDAD='EXTRCNCTVDD0040' ORDER BY PARAMETRO;
